{
  "formatVersion": "1.1",
  "component": {
    "group": "com.rarnu",
    "module": "android-jvm",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2",
      "buildId": "rj6jzca3vre2bdfgzrid263ti4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.rarnu",
          "module": "common-jvm",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.handmark.pulltorefresh.library",
          "module": "PullToRefresh",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "android-jvm-1.0.0.jar",
          "url": "android-jvm-1.0.0.jar",
          "size": 69138,
          "sha512": "5172706e8a3b10b7b7bb2c13a166ef8d57282e0f81503554b901700930fd475b9a74d062d2c6d284fb133efbe50b37a87219dd88267785d1bc97aacd98766886",
          "sha256": "d606a9eb999399bfe580225fdd7c01b1edebbe71f5f95a7f39daee304fecdf15",
          "sha1": "13a87491914876ff5621ac7be16c36f20c78cf92",
          "md5": "dfb04a6848c1ffa43789a50498f3046e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.61"
          }
        },
        {
          "group": "com.rarnu",
          "module": "common-jvm",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.handmark.pulltorefresh.library",
          "module": "PullToRefresh",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "android-jvm-1.0.0.jar",
          "url": "android-jvm-1.0.0.jar",
          "size": 69138,
          "sha512": "5172706e8a3b10b7b7bb2c13a166ef8d57282e0f81503554b901700930fd475b9a74d062d2c6d284fb133efbe50b37a87219dd88267785d1bc97aacd98766886",
          "sha256": "d606a9eb999399bfe580225fdd7c01b1edebbe71f5f95a7f39daee304fecdf15",
          "sha1": "13a87491914876ff5621ac7be16c36f20c78cf92",
          "md5": "dfb04a6848c1ffa43789a50498f3046e"
        }
      ]
    }
  ]
}
