{
  "formatVersion": "1.1",
  "component": {
    "group": "com.rarnu",
    "module": "ktor-jvm",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2",
      "buildId": "q4r7vrmx5neyrh25zd3eqk6enm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.ktor",
          "module": "ktor-server-core",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.rarnu",
          "module": "common-jvm",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-tomcat",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-host-common",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-sessions",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-jvm-1.0.0.jar",
          "url": "ktor-jvm-1.0.0.jar",
          "size": 50295,
          "sha512": "c3c58ed3920cd8b101a1f1550d33beb335cf009ef1a57817db792b15bb05d598d41232236e036e3d554a687f8b82d9948a2d493fe879f6327cf6917aaa27b143",
          "sha256": "638faea0a5cdb5b52a152dbb2c6ffaa00ac3059dd7d2857239eb57df7441fa58",
          "sha1": "71aad30ca671d9d90a7930dc7b6ec47b4b5cfcef",
          "md5": "69590c69205d4122f56d1e34e178f44d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.61"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-core",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.rarnu",
          "module": "common-jvm",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-tomcat",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-host-common",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-sessions",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-jvm-1.0.0.jar",
          "url": "ktor-jvm-1.0.0.jar",
          "size": 50295,
          "sha512": "c3c58ed3920cd8b101a1f1550d33beb335cf009ef1a57817db792b15bb05d598d41232236e036e3d554a687f8b82d9948a2d493fe879f6327cf6917aaa27b143",
          "sha256": "638faea0a5cdb5b52a152dbb2c6ffaa00ac3059dd7d2857239eb57df7441fa58",
          "sha1": "71aad30ca671d9d90a7930dc7b6ec47b4b5cfcef",
          "md5": "69590c69205d4122f56d1e34e178f44d"
        }
      ]
    }
  ]
}
