{
  "formatVersion": "1.1",
  "component": {
    "group": "com.rarnu",
    "module": "common-jvm",
    "version": "0.8.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2",
      "buildId": "7a7vgtrkcvgwdcvdlroyfbott4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.0.1"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.6"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-compress",
          "version": {
            "requires": "1.16.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.7"
          }
        },
        {
          "group": "org.json",
          "module": "json",
          "version": {
            "requires": "20180813"
          }
        },
        {
          "group": "org.jsoup",
          "module": "jsoup",
          "version": {
            "requires": "1.12.1"
          }
        }
      ],
      "files": [
        {
          "name": "common-jvm-0.8.0.jar",
          "url": "common-jvm-0.8.0.jar",
          "size": 87607,
          "sha512": "7168a915b60fafb617681b86c5c33246c0f9358ccbe8287b158a2f1db8e24a4cfd5ea753ea34a7e78bff8bdc3daf84dc5b9cbddf38e02b3f07bc0a9b258fa446",
          "sha256": "f108ca953cb2a3c5380f69b5fe4e937dddcbc86be0ee5881d2577b33b848ef1d",
          "sha1": "a91d2212691efb699da1fc7961dc83abd79f0e50",
          "md5": "56f435dd81a88050dd2b528876b06e11"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.61"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-junit",
          "version": {
            "requires": "1.3.61"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.0.1"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.6"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-compress",
          "version": {
            "requires": "1.16.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.7"
          }
        },
        {
          "group": "org.json",
          "module": "json",
          "version": {
            "requires": "20180813"
          }
        },
        {
          "group": "org.jsoup",
          "module": "jsoup",
          "version": {
            "requires": "1.12.1"
          }
        }
      ],
      "files": [
        {
          "name": "common-jvm-0.8.0.jar",
          "url": "common-jvm-0.8.0.jar",
          "size": 87607,
          "sha512": "7168a915b60fafb617681b86c5c33246c0f9358ccbe8287b158a2f1db8e24a4cfd5ea753ea34a7e78bff8bdc3daf84dc5b9cbddf38e02b3f07bc0a9b258fa446",
          "sha256": "f108ca953cb2a3c5380f69b5fe4e937dddcbc86be0ee5881d2577b33b848ef1d",
          "sha1": "a91d2212691efb699da1fc7961dc83abd79f0e50",
          "md5": "56f435dd81a88050dd2b528876b06e11"
        }
      ]
    }
  ]
}
