{
  "formatVersion": "1.1",
  "component": {
    "group": "com.rarnu",
    "module": "android-jvm",
    "version": "1.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2",
      "buildId": "fmxkefxhmfbmngespn7uh2oiyu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.rarnu",
          "module": "common-jvm",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.handmark.pulltorefresh.library",
          "module": "PullToRefresh",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "android-jvm-1.1.0.jar",
          "url": "android-jvm-1.1.0.jar",
          "size": 68868,
          "sha512": "f7218c858503ea837675402e3c65dac07f6c4333095449558a5c5a7d496201871b1d74474ebb53e5f30e0f587e99d1d7a31e17dd13e921063bee313e82186098",
          "sha256": "bc455047be0ebf92e0db591cccee765735c08512ec88923737b98019bc4e0d42",
          "sha1": "c725fe890ef04edb014db71532be0bf9be55b082",
          "md5": "8a813382bfa39df517fb43b936accae4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.rarnu",
          "module": "common-jvm",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.handmark.pulltorefresh.library",
          "module": "PullToRefresh",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "android-jvm-1.1.0.jar",
          "url": "android-jvm-1.1.0.jar",
          "size": 68868,
          "sha512": "f7218c858503ea837675402e3c65dac07f6c4333095449558a5c5a7d496201871b1d74474ebb53e5f30e0f587e99d1d7a31e17dd13e921063bee313e82186098",
          "sha256": "bc455047be0ebf92e0db591cccee765735c08512ec88923737b98019bc4e0d42",
          "sha1": "c725fe890ef04edb014db71532be0bf9be55b082",
          "md5": "8a813382bfa39df517fb43b936accae4"
        }
      ]
    }
  ]
}
