{
  "formatVersion": "1.1",
  "component": {
    "group": "com.rarnu",
    "module": "ktor-jvm",
    "version": "1.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2",
      "buildId": "kc55y7trbfcotmhjvgj5bzqgxy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.rarnu",
          "module": "common-jvm",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-core",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-tomcat",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-host-common",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-sessions",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-jvm-1.1.0.jar",
          "url": "ktor-jvm-1.1.0.jar",
          "size": 50121,
          "sha512": "b30ae584dd7ca3906b8e31cb8604184e014b37bf777c3323d1561af0ad053747d7f168b984860e61bec83fbbece170cff32c4982c3918fde1115865a45c10377",
          "sha256": "4be41d955de23de05b75ef2dfe943d0d737101e4766d8b0f45ab37cc51b1c199",
          "sha1": "c12b8498497db791e5970fa2cdda42ff71f61124",
          "md5": "ce973620deec9172e6a51322cf91869d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.rarnu",
          "module": "common-jvm",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-core",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-tomcat",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-host-common",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-sessions",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-jvm-1.1.0.jar",
          "url": "ktor-jvm-1.1.0.jar",
          "size": 50121,
          "sha512": "b30ae584dd7ca3906b8e31cb8604184e014b37bf777c3323d1561af0ad053747d7f168b984860e61bec83fbbece170cff32c4982c3918fde1115865a45c10377",
          "sha256": "4be41d955de23de05b75ef2dfe943d0d737101e4766d8b0f45ab37cc51b1c199",
          "sha1": "c12b8498497db791e5970fa2cdda42ff71f61124",
          "md5": "ce973620deec9172e6a51322cf91869d"
        }
      ]
    }
  ]
}
