{
  "formatVersion": "1.1",
  "component": {
    "group": "com.rarnu",
    "module": "ktor-jvm",
    "version": "1.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2",
      "buildId": "kturykrorzgi5ouspvzs2y57wa"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.rarnu",
          "module": "common-jvm",
          "version": {
            "requires": "1.1.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-core",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-tomcat",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-host-common",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-sessions",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-locations",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-gson",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-jvm-1.1.2.jar",
          "url": "ktor-jvm-1.1.2.jar",
          "size": 66209,
          "sha512": "6370a3ab741b46cd4044eae8be3ad8b73e0f2943e1f3948a9ae82c1f6d0d72ccb9ac66e5c0afe326fba2e19d5688ebc3e439b75261054fbb4c68e83f6c6d11b8",
          "sha256": "6b5f299ac837d006d6899e7306682e6bc4ff5cbfc3eeb30dd21ccf15a8432bd0",
          "sha1": "0f20df5354460fc1c844647f373b29997f95f001",
          "md5": "d2bf469e6c7ce697283cb68423ff29b6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.rarnu",
          "module": "common-jvm",
          "version": {
            "requires": "1.1.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-core",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-tomcat",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-host-common",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-sessions",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-locations",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-gson",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-jvm-1.1.2.jar",
          "url": "ktor-jvm-1.1.2.jar",
          "size": 66209,
          "sha512": "6370a3ab741b46cd4044eae8be3ad8b73e0f2943e1f3948a9ae82c1f6d0d72ccb9ac66e5c0afe326fba2e19d5688ebc3e439b75261054fbb4c68e83f6c6d11b8",
          "sha256": "6b5f299ac837d006d6899e7306682e6bc4ff5cbfc3eeb30dd21ccf15a8432bd0",
          "sha1": "0f20df5354460fc1c844647f373b29997f95f001",
          "md5": "d2bf469e6c7ce697283cb68423ff29b6"
        }
      ]
    }
  ]
}
