{
  "formatVersion": "1.1",
  "component": {
    "group": "com.rarnu",
    "module": "common-jvm",
    "version": "1.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2",
      "buildId": "ko3eb4bd2zcajkbhbsdwkpv6iu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.8.1"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.7"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-compress",
          "version": {
            "requires": "1.20"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.11"
          }
        },
        {
          "group": "org.jsoup",
          "module": "jsoup",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "common-jvm-1.1.2.jar",
          "url": "common-jvm-1.1.2.jar",
          "size": 176137,
          "sha512": "b297a84a7b02831b39038ab1299412308b4ebf051e1499d66f436f59381ef6494bf674bf4380b70a19bb48f17d3a686997ac26e4af38129f2ccf1f9f1192512b",
          "sha256": "af34b1ebe24bc07f577cd711680fcef99012f032e7d2365dae7daaa6e78a766e",
          "sha1": "3b049950992b172682971eb71e527c696d118991",
          "md5": "916631f48dfd45bad0e432f2d0d41a35"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.8.1"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.7"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-compress",
          "version": {
            "requires": "1.20"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.11"
          }
        },
        {
          "group": "org.jsoup",
          "module": "jsoup",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "common-jvm-1.1.2.jar",
          "url": "common-jvm-1.1.2.jar",
          "size": 176137,
          "sha512": "b297a84a7b02831b39038ab1299412308b4ebf051e1499d66f436f59381ef6494bf674bf4380b70a19bb48f17d3a686997ac26e4af38129f2ccf1f9f1192512b",
          "sha256": "af34b1ebe24bc07f577cd711680fcef99012f032e7d2365dae7daaa6e78a766e",
          "sha1": "3b049950992b172682971eb71e527c696d118991",
          "md5": "916631f48dfd45bad0e432f2d0d41a35"
        }
      ]
    }
  ]
}
