{
  "formatVersion": "1.1",
  "component": {
    "group": "com.rarnu",
    "module": "common-jvm",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2",
      "buildId": "fzrx37b5ungk3la6vxhbkonuaa"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.0.1"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.6"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-compress",
          "version": {
            "requires": "1.16.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.7"
          }
        },
        {
          "group": "org.json",
          "module": "json",
          "version": {
            "requires": "20180813"
          }
        },
        {
          "group": "org.jsoup",
          "module": "jsoup",
          "version": {
            "requires": "1.12.1"
          }
        }
      ],
      "files": [
        {
          "name": "common-jvm-1.0.0.jar",
          "url": "common-jvm-1.0.0.jar",
          "size": 89186,
          "sha512": "7a55186b3289b8f5161651e24bacc803b97c1b1bc77ba7adbb2e3645799fc409659e72e08b2b6036d308a7e0c652e8f5f7940cda0fff0c742e956d657dec59a9",
          "sha256": "80c7109d837c9dccd5b2206241b00d16cdafbe6ed02f8229cb240007a6e41d34",
          "sha1": "551d5d5852e5d76de940cd585fbff3cfa5262f7b",
          "md5": "8240b9ce90f960d8d8d0561883020b8b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.61"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-junit",
          "version": {
            "requires": "1.3.61"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.0.1"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.6"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-compress",
          "version": {
            "requires": "1.16.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.7"
          }
        },
        {
          "group": "org.json",
          "module": "json",
          "version": {
            "requires": "20180813"
          }
        },
        {
          "group": "org.jsoup",
          "module": "jsoup",
          "version": {
            "requires": "1.12.1"
          }
        }
      ],
      "files": [
        {
          "name": "common-jvm-1.0.0.jar",
          "url": "common-jvm-1.0.0.jar",
          "size": 89186,
          "sha512": "7a55186b3289b8f5161651e24bacc803b97c1b1bc77ba7adbb2e3645799fc409659e72e08b2b6036d308a7e0c652e8f5f7940cda0fff0c742e956d657dec59a9",
          "sha256": "80c7109d837c9dccd5b2206241b00d16cdafbe6ed02f8229cb240007a6e41d34",
          "sha1": "551d5d5852e5d76de940cd585fbff3cfa5262f7b",
          "md5": "8240b9ce90f960d8d8d0561883020b8b"
        }
      ]
    }
  ]
}
